export const ERRORS = "ERRORS";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";

export const CREATE_LAUNCHPAD_REQUEST = "CREATE_LAUNCHPAD_REQUEST";
export const CREATE_LAUNCHPAD_SUCCESS = "CREATE_LAUNCHPAD_SUCCESS";
export const CREATE_LAUNCHPAD_FAILURE = "CREATE_LAUNCHPAD_FAILURE";

export const UPDATE_LAUNCHPAD_REQUEST = "UPDATE_LAUNCHPAD_REQUEST";
export const UPDATE_LAUNCHPAD_SUCCESS = "UPDATE_LAUNCHPAD_SUCCESS";
export const UPDATE_LAUNCHPAD_FAILURE = "UPDATE_LAUNCHPAD_FAILURE";

export const REMOVE_LAUNCHPAD_REQUEST = "REMOVE_LAUNCHPAD_REQUEST";
export const REMOVE_LAUNCHPAD_SUCCESS = "REMOVE_LAUNCHPAD_SUCCESS";
export const REMOVE_LAUNCHPAD_FAILURE = "REMOVE_LAUNCHPAD_FAILURE";

export const TOGGLE_LAUNCHPAD_SUCCESS = "TOGGLE_LAUNCHPAD_SUCCESS";
export const TOGGLE_LAUNCHPAD_REQUEST = "TOGGLE_LAUNCHPAD_REQUEST";
export const TOGGLE_LAUNCHPAD_FAILURE = "TOGGLE_LAUNCHPAD_FAILURE";

export const GET_LAUNCHPAD_OPTION_REQUEST = "GET_LAUNCHPAD_OPTION_REQUEST";
export const GET_LAUNCHPAD_OPTION_SUCCESS = "GET_LAUNCHPAD_OPTION_SUCCESS";
export const GET_LAUNCHPAD_OPTION_FAILURE = "GET_LAUNCHPAD_OPTION_FAILURE";
