export const ERRORS = "ERRORS";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";

export const CREATE_LAUNCHPAD_REQUEST = "CREATE_LAUNCHPAD_REQUEST";
export const CREATE_LAUNCHPAD_SUCCESS = "CREATE_LAUNCHPAD_SUCCESS";
export const CREATE_LAUNCHPAD_FAILURE = "CREATE_LAUNCHPAD_FAILURE";

export const UPDATE_LAUNCHPAD_REQUEST = "UPDATE_LAUNCHPAD_REQUEST";
export const UPDATE_LAUNCHPAD_SUCCESS = "UPDATE_LAUNCHPAD_SUCCESS";
export const UPDATE_LAUNCHPAD_FAILURE = "UPDATE_LAUNCHPAD_FAILURE";

export const REMOVE_LAUNCHPAD_REQUEST = "REMOVE_LAUNCHPAD_REQUEST";
export const REMOVE_LAUNCHPAD_SUCCESS = "REMOVE_LAUNCHPAD_SUCCESS";
export const REMOVE_LAUNCHPAD_FAILURE = "REMOVE_LAUNCHPAD_FAILURE";

export const TOGGLE_LAUNCHPAD_SUCCESS = "TOGGLE_LAUNCHPAD_SUCCESS";
export const TOGGLE_LAUNCHPAD_REQUEST = "TOGGLE_LAUNCHPAD_REQUEST";
export const TOGGLE_LAUNCHPAD_FAILURE = "TOGGLE_LAUNCHPAD_FAILURE";

export const GET_LAUNCHPAD_OPTION_REQUEST = "GET_LAUNCHPAD_OPTION_REQUEST";
export const GET_LAUNCHPAD_OPTION_SUCCESS = "GET_LAUNCHPAD_OPTION_SUCCESS";
export const GET_LAUNCHPAD_OPTION_FAILURE = "GET_LAUNCHPAD_OPTION_FAILURE";

export const GET_TOKEN_DETAILS_REQUEST = "GET_TOKEN_DETAILS_REQUEST";
export const GET_TOKEN_DETAILS_SUCCESS = "GET_TOKEN_DETAILS_SUCCESS";
export const GET_TOKEN_DETAILS_FAILURE = "GET_TOKEN_DETAILS_FAILURE";

export const DEPLOY_LAUNCHPAD_REQUEST = "DEPLOY_LAUNCHPAD_REQUEST";
export const DEPLOY_LAUNCHPAD_SUCCESS = "DEPLOY_LAUNCHPAD_SUCCESS";
export const DEPLOY_LAUNCHPAD_FAILURE = "DEPLOY_LAUNCHPAD_FAILURE";

export const CLEAR_TOKEN_RESPONSE = "CLEAR_TOKEN_RESPONSE";
export const CLEAR_STAGE_RESPONSE = "CLEAR_STAGE_RESPONSE";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

export const UPDATE_LAUNCHPAD_ACTIVE_REQUEST =
	"UPDATE_LAUNCHPAD_ACTIVE_REQUEST";
export const UPDATE_LAUNCHPAD_ACTIVE_SUCCESS =
	"UPDATE_LAUNCHPAD_ACTIVE_SUCCESS";
export const UPDATE_LAUNCHPAD_ACTIVE_FAILURE =
	"UPDATE_LAUNCHPAD_ACTIVE_FAILURE";

export const GET_LAUNCHPAD_REQUEST = "GET_LAUNCHPAD_REQUEST";
export const GET_LAUNCHPAD_SUCCESS = "GET_LAUNCHPAD_SUCCESS";
export const GET_LAUNCHPAD_FAILURE = "GET_LAUNCHPAD_FAILURE";

export const GET_NETWORK_INFO_REQUEST = "GET_NETWORK_INFO_REQUEST";
export const GET_NETWORK_INFO_SUCCESS = "GET_NETWORK_INFO_SUCCESS";
export const GET_NETWORK_INFO_FAILURE = "GET_NETWORK_INFO_FAILURE";

export const CONTINUE_LAUNCHPAD_DEPLOY_HISTORY_REQUEST =
	"CONTINUE_LAUNCHPAD_DEPLOY_HISTORY_REQUEST";

export const CONTINUE_LAUNCHPAD_DEPLOY_HISTORY_SUCCESS =
	"CONTINUE_LAUNCHPAD_DEPLOY_HISTORY_SUCCESS";

export const GET_LAUNCHPAD_DEPLOY_HISTORY_REQUEST =
	"GET_LAUNCHPAD_DEPLOY_HISTORY_REQUEST";

export const GET_LAUNCHPAD_DEPLOY_HISTORY_SUCCESS =
	"GET_LAUNCHPAD_DEPLOY_HISTORY_SUCCESS";
export const GET_LAUNCHPAD_DEPLOY_HISTORY_FAILURE =
	"GET_LAUNCHPAD_DEPLOY_HISTORY_FAILURE";

export const TOGGLE_SWAP_REQUEST = "TOGGLE_SWAP_REQUEST";
export const TOGGLE_SWAP_SUCCESS = "TOGGLE_SWAP_SUCCESS";
export const TOGGLE_SWAP_FAILURE = "TOGGLE_SWAP_FAILURE";

export const UPDATE_STAGE_REQUEST = "UPDATE_STAGE_REQUEST";
export const UPDATE_STAGE_SUCCESS = "UPDATE_STAGE_SUCCESS";
export const UPDATE_STAGE_FAILURE = "UPDATE_STAGE_FAILURE";

export const TOGGLE_STAGE_SWAP_REQUEST = "TOGGLE_STAGE_SWAP_REQUEST";
export const TOGGLE_STAGE_SWAP_SUCCESS = "TOGGLE_STAGE_SWAP_SUCCESS";
export const TOGGLE_STAGE_SWAP_FAILURE = "TOGGLE_STAGE_SWAP_FAILURE";

export const DEPLOY_UPDATED_STAGE_REQUEST = "DEPLOY_UPDATED_STAGE_REQUEST";
export const DEPLOY_UPDATED_STAGE_SUCCESS = "DEPLOY_UPDATED_STAGE_SUCCESS";
export const DEPLOY_UPDATED_STAGE_FAILURE = "DEPLOY_UPDATED_STAGE_FAILURE";

export const GET_UPDATED_LAUNCHPAD_REQUEST = "GET_UPDATED_LAUNCHPAD_REQUEST";
export const GET_UPDATED_LAUNCHPAD_SUCCESS = "GET_UPDATED_LAUNCHPAD_SUCCESS";
export const GET_UPDATED_LAUNCHPAD_FAILURE = "GET_UPDATED_LAUNCHPAD_FAILURE";

export const GET_LAUCHPAD_STAGES_REQUEST = "GET_LAUCHPAD_STAGES_REQUEST";
export const GET_LAUCHPAD_STAGES_SUCCESS = "GET_LAUCHPAD_STAGES_SUCCESS";
export const GET_LAUCHPAD_STAGES_FAILURE = "GET_LAUCHPAD_STAGES_FAILURE";
