export const ERRORS = "ERRORS";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";

export const GET_TOTAL_LAUNCHPAD_REQUEST = "GET_TOTAL_LAUNCHPAD_REQUEST";
export const GET_TOTAL_LAUNCHPAD_SUCCESS = "GET_TOTAL_LAUNCHPAD_SUCCESS";
export const GET_TOTAL_LAUNCHPAD_FAILURE = "GET_TOTAL_LAUNCHPAD_FAILURE";
